
import React from 'react';

const Page = () => {
  return (
    <div className="max-w-4xl mx-auto bg-white text-black shadow-lg rounded-lg p-4 mt-10">
      <h1 className="text-3xl font-semibold text-center text-gray-500 mb-4">Privacy Policy for Coder Collective</h1>
      
      <p className="text-sm text-right text-gray-500 mb-6">Last Updated: October 4th, 2024</p>
      
      <p className="mb-4">Welcome to Coder Collective! We respect your privacy and are committed to protecting your personal information. This privacy policy outlines how we collect, use, protect, and disclose your information.</p>
      
      <h2 className="text-2xl font-semibold text-gray-500 mt-6 mb-2">1. Information We Collect</h2>
      <ul className="list-disc list-inside mb-4">
        <li><strong>Personal Information</strong>: This includes your name, contact details, professional details, and any other information you provide when signing up, referring candidates, or introducing clients.</li>
        <li><strong>Usage Data</strong>: We collect data generated by your interactions with our website, such as referral statistics, website navigation paths, and dashboard usage.</li>
        <li><strong>Cookies</strong>: Our website uses cookies to enhance user experience and track website usage patterns.</li>
      </ul>
      
      <h2 className="text-2xl font-semibold text-gray-500 mt-6 mb-2">2. How We Use Your Information</h2>
      <ul className="list-disc list-inside mb-4">
        <li>To provide and manage our services, including the referral program and user dashboard.</li>
        <li>We may display your basic contact details, such as your first name, last name, and profile picture, on our website as part of our referral process. This is to enable clients or candidates you've introduced to accurately identify and select you as their referrer in the Coder Collective network.</li>
        <li>Whenever you provide contact information for referrals or client introductions, we will include you in the CC (carbon copy) field of any emails sent in relation to these introductions. This ensures you stay informed about the communications initiated through your referrals.</li>
        <li>For communication purposes, such as responding to inquiries and sending updates about our services.</li>
        <li>To improve our website and tailor it to user preferences.</li>
        <li>For compliance with legal obligations and protection against fraudulent activities.</li>
      </ul>
      
      <h2 className="text-2xl font-semibold text-gray-500 mt-6 mb-2">3. Sharing Your Information</h2>
      <ul className="list-disc list-inside mb-4">
        <li>We do not sell your personal information.</li>
        <li>We may share information with trusted third parties who assist us in operating our website, conducting our business, or servicing you, as long as those parties agree to keep this information confidential.</li>
        <li>We may also release your information when we believe release is appropriate to comply with the law, enforce our site policies, or protect ours or others' rights, property, or safety.</li>
      </ul>
      
      <h2 className="text-2xl font-semibold text-gray-500 mt-6 mb-2">4. Data Security</h2>
      <ul className="list-disc list-inside mb-4">
        <li>We implement a variety of security measures to maintain the safety of your personal information.</li>
        <li>Your personal information is contained behind secured networks and is only accessible by a limited number of persons who have special access rights to such systems.</li>
      </ul>
      
      <h2 className="text-2xl font-semibold text-gray-500 mt-6 mb-2">5. Your Rights</h2>
      <ul className="list-disc list-inside mb-4">
        <li>You have the right to access, update, or delete the personal information we hold about you.</li>
        <li>You can opt-out of receiving marketing communications from us.</li>
      </ul>
      
      <h2 className="text-2xl font-semibold text-gray-500 mt-6 mb-2">6. Changes to This Privacy Policy</h2>
      <p className="mb-4">We may update this privacy policy from time to time. We will notify you of any changes by posting the new privacy policy on this page.</p>
      
      <h2 className="text-2xl font-semibold text-gray-500 mt-6 mb-2">7. Contact Us</h2>
      <p className="mb-6">If you have any questions about this privacy policy, please contact us at referrals@thecodercollective.com. </p>
      
    </div>
  );
};

export default Page;