import { type PastCompaniesIdsMapType, PastCompany } from '@/lib/types';

export const workArrangement = ['Remote', 'Onsite', 'Hybrid'];

export const jobTypes = ['Full-time', 'Contract-To-Hire', 'Contract'];

export const geos = [
  { label: 'SF Bay Area', value: '90000084' },
  { label: 'Chicago', value: '90000014' },
  { label: 'SLC', value: '90000716' },
  { label: 'Houston', value: '90000042' },
  { label: 'Atlanta', value: '90000052' },
  { label: 'Boston', value: '90000007' },
  { label: 'NYC', value: '90000070' },
  { label: 'Washington DC', value: '90000097' },
  { label: 'San Diego', value: '90010472' },
];

export const industries = [
  'Aerospace and Aviation',
  'Agriculture',
  'Artificial Intelligence (AI)',
  'Automated Technology',
  'Automotive',
  'Banking',
  'Biotechnology',
  'Blockchain and Cryptocurrency',
  'Chemical Manufacturing',
  'Civil Engineering',
  'Clothing and Textile Manufacturing',
  'Construction',
  'Consulting',
  'Consumer Goods Manufacturing',
  'Culinary and Food Services',
  'Cybersecurity',
  'Data Analytics',
  'Education',
  'Electronics Manufacturing',
  'Energy',
  'Entertainment and Media',
  'Environmental Services',
  'Fashion and Apparel',
  'Financial Services',
  'Financial Technology (FinTech)',
  'Food and Beverage Manufacturing',
  'Forestry and Logging',
  'Government',
  'Healthcare',
  'Heavy Machinery Manufacturing',
  'Hospitality',
  'Information Technology',
  'Insurance',
  'Internet and Software',
  'Legal',
  'Manufacturing',
  'Marketing and Advertising',
  'Medical Devices',
  'Metal Manufacturing',
  'Mining and Extraction',
  'Music and Performing Arts',
  'Nanotechnology',
  'Nonprofit and Social Services',
  'Oil and Gas',
  'Paper and Packaging Manufacturing',
  'Pharmaceuticals',
  'Plastics Manufacturing',
  'Real Estate',
  'Renewable Energy',
  'Retail',
  'Robotics',
  'Sports and Recreation',
  'Telecommunications',
  'Textile Manufacturing',
  'Transportation and Logistics',
  'Venture Capital & Private Equity',
  'Virtual and Augmented Reality',
];

export const states = [
  'Alabama (AL)',
  'Alaska (AK)',
  'Arizona (AZ)',
  'Arkansas (AR)',
  'California (CA)',
  'Colorado (CO)',
  'Connecticut (CT)',
  'Delaware (DE)',
  'Florida (FL)',
  'Georgia (GA)',
  'Hawaii (HI)',
  'Idaho (ID)',
  'Illinois (IL)',
  'Indiana (IN)',
  'Iowa (IA)',
  'Kansas (KS)',
  'Kentucky (KY)',
  'Louisiana (LA)',
  'Maine (ME)',
  'Maryland (MD)',
  'Massachusetts (MA)',
  'Michigan (MI)',
  'Minnesota (MN)',
  'Mississippi (MS)',
  'Missouri (MO)',
  'Montana (MT)',
  'Nebraska (NE)',
  'Nevada (NV)',
  'New Hampshire (NH)',
  'New Jersey (NJ)',
  'New Mexico (NM)',
  'New York (NY)',
  'North Carolina (NC)',
  'North Dakota (ND)',
  'Ohio (OH)',
  'Oklahoma (OK)',
  'Oregon (OR)',
  'Pennsylvania (PA)',
  'Rhode Island (RI)',
  'South Carolina (SC)',
  'South Dakota (SD)',
  'Tennessee (TN)',
  'Texas (TX)',
  'Utah (UT)',
  'Vermont (VT)',
  'Virginia (VA)',
  'Washington (WA)',
  'West Virginia (WV)',
  'Wisconsin (WI)',
  'Wyoming (WY)',
];

export const pastCompanies: PastCompany[] = [
  { label: 'KPMG', checked: false },
  { label: 'EY', checked: false },
  { label: 'Deloitte', checked: false },
  { label: 'PwC', checked: false },
];

export const pastCompaniesIdsMap: PastCompaniesIdsMapType = {
  KPMG: '2525300',
  EY: '1073',
  Deloitte: '1038',
  PwC: '1044',
};



// Constants
export const areasOfExpertise = [
  { name: 'Frontend Development' },
  { name: 'Backend Development' },
  { name: 'DevOps' },
  { name: 'AI/ML' },
  { name: 'Product Management' },
  { name: 'Mobile Development' },
  { name: 'Data Engineering' },
  { name: 'UI/UX Design' },
];

